### ISSUE TITLE
Using existing BenchmarkJS Benchmarks + Suites

### ISSUE THREAD

**Issue by sdesai** [JamieMason/karma-benchmark#8]
If I want to use karma-benchmark to drive an existing set of benchmark tests, do I need to refactor all my existing tests which currently use the BenchmarkJS Benchmark and Suite objects, to use the "global" benchmark() and suite() wrappers which karma-benchmark introduces to register my tests?

It seems like, at some point in the past, karma-benchmark used to allow users to use the BenchmarkJS APIs (https://groups.google.com/d/msg/karma-users/sreRuEnUp6k/D-EYDd8RCzQJ) as opposed to forcing tests to be updated to use the "global" benchmark() and suite().

Just wondering if that support still exists or not?

**Comment by JamieMason** [comment]
Thanks @sdesai, there were some major changes in pull request https://github.com/JamieMason/karma-benchmark/pull/3 which I think affected this. 

It's been a long while since I've worked on karma-benchmark, but once I've finished what I'm doing on [shrinkpack](https://github.com/JamieMason/shrinkpack) and [ImageOptim-CLI](https://github.com/JamieMason/ImageOptim-CLI) I plan to pick this back up again in a couple of months.

**Comment by pauldraper** [comment]
+1

**Comment by JamieMason** [comment]
Released in 0.7.1, please let me know if you run into any issues @sdesai.
